twig:
    globals:
        google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    paths: 
        '%kernel.project_dir%/templates':
        '%kernel.project_dir%/src/JoesBundle/Resources/views/contacts': theme
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'    
    form_themes: ['bootstrap_3_layout.html.twig']
