twig:
    paths: 
        '%kernel.project_dir%/templates':
        '%kernel.project_dir%/src/JoesBundle/Resources/views/contacts': theme
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
